export default {
    "og:title": "PRTS",
	"og:description": "Just an another Arknights toolbox. Currently in developement.",
	"og:site_name": "Primitive Rhodes Island Terminal Service",
	"og:type": "profile",
	//"og:url": "https://prts.tech",
	"og:url": "https://beta.prts.tech",
	"og:image": "https://beta.prts.tech/assets/img/opengraph-beta.png",
	"og:image:type": "image/png",
	"og:image:width": "1200",
	"og:image:height": "630",
	"og:image:alt": "PRTS BG",
	"fb:app_id": "216805307148987",
	"twitter:card": "summary_large_image",
	"twitter:site": "@kawatoriSayuri",
	"twitter:creator": "@kawatoriSayuri",
	"twitter:title": "PRTS",
	"twitter:description": "Just an another Arknights toolbox. Currently in developement.",
	"twitter:image:src": "https://beta.prts.tech/assets/img/opengraph-beta.png",
	"twitter:image:width": "1200",
	"twitter:image:height": "630",
}
